FROM docker.io/library/debian@sha256:675b032d19e294c9eb2525b24ee63e6dc718854a481c6fd6f5e0aefcaf8208a1

RUN apt-get update \
    && apt-get install --yes --no-install-recommends bash curl gh git python3 rsync \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
