FROM docker.io/library/node@sha256:53ada149d435c38b14476cb57e4a7da73c15595aba79bd6971b547ceb6d018bf

RUN apt-get update \
    && apt-get install --yes --no-install-recommends bash curl gh git python3 rsync \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
